### Get all tags
GET http://localhost:3000/tags

### Create a new tag
POST http://localhost:3000/tags
Content-Type: application/json

{
	"name": "Tag 4"
}

### Find a specific tag
GET http://localhost:3000/tags/1

### Update a new tag
PATCH http://localhost:3000/tags/3
Content-Type: application/json

{
	"name": "Updated Tag 3"
}

### Remove a specific tag
DELETE http://localhost:3000/tags/4
