services:
#  sample_db:
#    image: mysql
#    container_name: sample_db
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: sample_db 
#    ports:
#      - "3306:3306"
#    restart: always
  pg_db:
    image: postgres
    restart: always
    container_name: pg_db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: notes
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

