### Get all users
GET http://localhost:3000/users

### Create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "admin21@gmail.com",
  "password": "aT67@sim20"
}
